# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://mazhuang.org/jekyll-theme-solid
date_format: "ordinal"
title: jekyll-theme-solid
author: Zhuang Ma 

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
paginate: 9
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: mzlogin
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin
    repo: jekyll-theme-solid
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: mzlogin
    repo: jekyll-theme-solid
    clientID: d2e1cbbd298958076462
    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false
